{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rstoolbox
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RStoolbox_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RStoolbox/RStoolbox_{{ version }}.tar.gz
  sha256: f19ff112d3f8d3cf7a8655e5c22be98ebab7d81b4a1fb750f570b551a71530ac

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-caret >=6.0_79
    - r-dplyr
    - r-exactextractr
    - r-ggplot2
    - r-lifecycle
    - r-rcpp
    - r-rcpparmadillo
    - r-reshape2
    - r-sf
    - r-terra >=1.6_41
    - r-xml
    - libblas
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-caret >=6.0_79
    - r-dplyr
    - r-exactextractr
    - r-ggplot2
    - r-lifecycle
    - r-rcpp
    - r-rcpparmadillo
    - r-reshape2
    - r-sf
    - r-terra >=1.6_41
    - r-xml

test:
  commands:
    - $R -e "library('RStoolbox')"           # [not win]
    - "\"%R%\" -e \"library('RStoolbox')\""  # [win]

about:
  home: https://bleutner.github.io/RStoolbox/
  dev_url: https://github.com/bleutner/RStoolbox
  license: GPL-3.0-or-later
  summary: Toolbox for remote sensing image processing and analysis such as calculating spectral indices, principal component transformation, unsupervised and supervised classification or fractional cover analyses.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - marie59
